name: lazy fridge deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}

      - name: Run Deployment
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: |
          export FLASK_ENV=production
          ssh -o StrictHostKeyChecking=no root@161.35.88.143 "rm -R lazy-fridge"
          ssh -o StrictHostKeyChecking=no root@161.35.88.143 "git clone https://github.com/annwhoorma/lazy-fridge"
          ssh -o StrictHostKeyChecking=no root@161.35.88.143 "sudo apt install Python3.10"
          ssh -o StrictHostKeyChecking=no root@161.35.88.143 "python3 -m pip install --upgrade pip"
          ssh -o StrictHostKeyChecking=no root@161.35.88.143 "pip install -r requirements.txt"
          ssh -o StrictHostKeyChecking=no root@161.35.88.143 "cd lazy-fridge/src && flask --app main run"
