name: lazy fridge deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}

      - name: Run Deployment
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: |
          export FLASK_ENV=production
          ssh -o StrictHostKeyChecking=no root@142.93.224.135 "cd lazy-fridge && git pull"
          ssh -o StrictHostKeyChecking=no root@142.93.224.135 "cd lazy-fridge && pip3 install -r requirements.txt"
          echo "TELEGRAM_TOKEN=$TELEGRAM_TOKEN" >> .env
          echo "NOTION_TOKEN=$NOTION_TOKEN" >> .env
          echo "DATABASE_ID=$DATABASE_ID" >> .env
          scp .env root@142.93.224.135:lazy-fridge/src
          ssh -o StrictHostKeyChecking=no root@142.93.224.135 "systemctl --user restart lazy-fridge-app"
